# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [49]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print("numpy version:", np.__version__)

print("numpy configuration:")
np.show_config()

numpy version: 1.26.0
numpy configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Nniki/miniconda3/envs/ida/Library/include
    lib directory: C:/Users/Nniki/miniconda3/envs/ida/Library/lib
    name: mkl-sdl
    pc file directory: C:\b\abs_9fu2cs2527\croot\numpy_and_numpy_base_1695830496596\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Nniki/miniconda3/envs/ida/Library/include
    lib directory: C:/Users/Nniki/miniconda3/envs/ida/Library/lib
    name: mkl-sdl
    pc file directory: C:\b\abs_9fu2cs2527\croot\numpy_and_numpy_base_1695830496596\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
    linker: cython
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [46]:
nullVector = np.zeros(10)
nullVector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [40]:
nullVector = np.zeros(10)
memorySize = nullVector.nbytes
memorySize

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
nullVector = np.zeros(10)
nullVector[4] = 1
nullVector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vector = np.arange(50)
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
vector = np.arange(10)
vector[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
vector = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(vector)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [19]:
matrix = np.eye(3)
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [20]:
matrix = np.random.rand(3, 3, 3)
matrix

array([[[0.6803265 , 0.79474602, 0.11245914],
        [0.34909303, 0.25264929, 0.14909818],
        [0.88970515, 0.34940983, 0.85004923]],

       [[0.91674604, 0.64929803, 0.56927756],
        [0.41709116, 0.9583393 , 0.99397726],
        [0.57111712, 0.96785459, 0.67627626]],

       [[0.78679277, 0.85425494, 0.64562366],
        [0.96526594, 0.64552738, 0.02306874],
        [0.98876796, 0.00670787, 0.70670614]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [32]:
matrix = np.random.rand(10, 10)
print(matrix)
print(matrix.min())
print(matrix.max())

[[0.67279145 0.91315257 0.86510983 0.96200606 0.3995672  0.64303205
  0.46850421 0.65305468 0.075142   0.64285022]
 [0.22259678 0.38656114 0.7821981  0.01007978 0.27787235 0.20741843
  0.85764185 0.62323825 0.76089732 0.57596908]
 [0.54524798 0.33202245 0.51986482 0.532777   0.75404154 0.34358728
  0.0080752  0.547754   0.82661136 0.70761621]
 [0.40823906 0.87943525 0.32216873 0.2297241  0.95866361 0.18621142
  0.90352581 0.78469951 0.86526106 0.18111784]
 [0.29367033 0.03130349 0.1719337  0.05919686 0.79135952 0.59524538
  0.577454   0.59167228 0.62362407 0.91993337]
 [0.23651657 0.95031804 0.04707825 0.39256211 0.48252964 0.97919013
  0.48639854 0.03638754 0.51516146 0.11270084]
 [0.09223448 0.78979071 0.60294497 0.9112127  0.49430326 0.25212879
  0.12654699 0.32516408 0.85751916 0.41805261]
 [0.83103    0.7995168  0.67949796 0.28752607 0.02480085 0.86272926
  0.86913027 0.55033076 0.72422769 0.1295404 ]
 [0.52823682 0.3222733  0.90740081 0.3869992  0.72417778 0.05171606
  0.03403529

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [35]:
vector = np.random.rand(30)
print(vector)
print(vector.mean())

[0.74858903 0.66799056 0.92923194 0.21844441 0.50287155 0.47383948
 0.02871845 0.10600911 0.78783487 0.90459694 0.81522615 0.06369706
 0.43173315 0.99681829 0.21802512 0.93028017 0.59213471 0.06509685
 0.06745689 0.14052965 0.97323541 0.83931567 0.05733569 0.20959314
 0.26264451 0.32874647 0.18596386 0.02642283 0.80877217 0.52558694]
0.4635580358167037


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [41]:
n = 7
matrix = np.ones((n, n))
matrix[1:-1, 1:-1] = 0
matrix

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [46]:
n = 3
matrix = np.random.rand(n, n)
matrix2 = np.zeros((n + 2, n + 2))
matrix2[1:-1, 1:-1] = matrix
matrix2

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.93068648, 0.87416624, 0.97743232, 0.        ],
       [0.        , 0.59633775, 0.22743292, 0.96589137, 0.        ],
       [0.        , 0.27745577, 0.78538585, 0.13480121, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [56]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [58]:
matrix = np.zeros((5, 5))
for i in range(1, 5):
    matrix[i, i - 1] = i
matrix

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [60]:
matrix = np.zeros((8, 8))
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1
matrix

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [62]:
shape = (6, 7, 8)
np.unravel_index(100, shape)

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [64]:
matrix = np.array(([0, 1], [1, 0]))
np.tile(matrix, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [91]:
matrix = np.random.rand(5, 5)

print('matrix:')
print(matrix)

matrix = (matrix - matrix.mean()) / matrix.std()

print('normalized matrix:')
print(matrix)
print(matrix.mean())

matrix:
[[0.95872519 0.54775152 0.4217005  0.62972895 0.12627178]
 [0.30768528 0.88822608 0.85336064 0.7264764  0.37186081]
 [0.42435712 0.94181956 0.94171815 0.92478936 0.9526232 ]
 [0.67003787 0.97817678 0.4884959  0.90783345 0.77725572]
 [0.89222431 0.67175593 0.93620785 0.44968469 0.31867146]]
normalized matrix:
[[ 1.0855296  -0.54012323 -1.03873227 -0.21585222 -2.20733399]
 [-1.48973239  0.8066624   0.66874819  0.16684325 -1.23587884]
 [-1.02822371  1.01865745  1.01825633  0.9512926   1.0613925 ]
 [-0.05640575  1.16247255 -0.77451553  0.88422157  0.36770661]
 [ 0.82247785 -0.04960975  0.99645973 -0.92803766 -1.4462753 ]]
3.730349362740526e-16


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [97]:
colorDType = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
color = np.array((255, 128, 0, 255), dtype = colorDType)
print(color)

(255, 128, 0, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [98]:
np.dot(np.random.rand(5, 3), np.random.rand(3,2))

array([[0.72843783, 0.9268155 ],
       [0.36479815, 0.38575442],
       [0.89285799, 0.9320498 ],
       [0.67283584, 0.62180515],
       [0.60752596, 0.72040168]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [101]:
vector = np.arange(10)
vector[(vector > 3) & (vector < 8)] *= -1
vector

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [105]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10


10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [116]:
Z = np.ones((5,))
Z**Z
# 2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z

array([1., 1., 1., 1., 1.])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [48]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Nniki\AppData\Local\Temp\ipykernel_10424\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Nniki\AppData\Local\Temp\ipykernel_10424\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Nniki\AppData\Local\Temp\ipykernel_10424\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [259]:
vector = np.random.random((5,5))
print(vector)
vector = np.round(vector, 2)
print(vector) 

[[0.00465231 0.94719821 0.29502261 0.04516614 0.44464673]
 [0.86299984 0.11462021 0.61915571 0.09505007 0.43575671]
 [0.77283846 0.57024888 0.48486534 0.13662468 0.69272926]
 [0.18906067 0.69057374 0.72465187 0.35722002 0.23207266]
 [0.88227596 0.36956868 0.72775535 0.27320842 0.72820797]]
[[0.   0.95 0.3  0.05 0.44]
 [0.86 0.11 0.62 0.1  0.44]
 [0.77 0.57 0.48 0.14 0.69]
 [0.19 0.69 0.72 0.36 0.23]
 [0.88 0.37 0.73 0.27 0.73]]


#### 30. How to find common values between two arrays? (★☆☆)

In [5]:
vector1 = np.arange(5)
vector2 = np.arange(3, 8)

print(vector1)
print(vector2)
print(np.intersect1d(vector1, vector2))

[0 1 2 3 4]
[3 4 5 6 7]
[3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [139]:
np.seterr(all = 'ignore')
# np.seterr(all = 'warn')

{'divide': 'warn', 'over': 'warn', 'under': 'warn', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [143]:
# np.sqrt(-1)
# np.emath.sqrt(-1)
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [145]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow  = today + np.timedelta64(1, 'D')

print(yesterday)
print(today)
print(tomorrow)

2023-10-03
2023-10-04
2023-10-05


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [148]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [8]:
A = np.ones(3) * 1
B = np.ones(3) * 2
# np.add(A, B, out = B)
# np.divide(-A, 2, out = A)
# np.dot(A, B)
np.dot((A + B), (-A / 2))

-4.5

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [10]:
vector = np.random.uniform(0, 10, 10)

print(vector)
print(vector - vector % 1)
print(np.floor(vector))
print(np.ceil(vector)-1)
print(vector.astype(int))

[5.03649168 3.34991819 4.48426526 8.99569413 7.2009882  8.70581116
 9.03818888 1.55029307 6.95795232 8.82750455]
[5. 3. 4. 8. 7. 8. 9. 1. 6. 8.]
[5. 3. 4. 8. 7. 8. 9. 1. 6. 8.]
[5. 3. 4. 8. 7. 8. 9. 1. 6. 8.]
[5 3 4 8 7 8 9 1 6 8]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [171]:
matrix = np.zeros((5,5))
matrix += np.arange(5)
matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [177]:
def generate():
    for x in range(10):
        yield x

vector = np.fromiter(generate(), dtype = int)
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [181]:
vector = np.linspace(0, 1, 11, endpoint = False)[1:]
vector

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [183]:
vector = np.random.rand(10)
vector.sort()
vector

array([0.003559  , 0.06671919, 0.23953647, 0.46715683, 0.46995529,
       0.48286577, 0.50558504, 0.50646812, 0.57447547, 0.66143704])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [232]:
vector = np.arange(100)
# np.sum(vector)
sum(vector)

4950

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [252]:
A = np.random.rand(5)
B = np.random.rand(5)
print(A)
print(B)

np.array_equal(A,B)

[0.98888216 0.19657337 0.58086038 0.98866033 0.81613337]
[0.86284428 0.08003717 0.00287327 0.85960219 0.60565539]


False

#### 43. Make an array immutable (read-only) (★★☆)

In [4]:
vector = np.zeros(10)
vector.flags.writeable = False
vector[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [275]:
matrix = np.random.rand(10, 2)

print(matrix)

x, y = matrix[:, 0], matrix[:, 1]

# Вычисляем радиус (расстояние от начала координат) и угол в радианах (арктангенс y/x)
radius = np.sqrt(x**2 + y**2)
angle = np.arctan2(y, x)

poles = np.c_[radius, angle ]
poles

[[0.23508135 0.56098431]
 [0.26214745 0.22406019]
 [0.24354069 0.68969811]
 [0.69014452 0.35475348]
 [0.67671391 0.50535278]
 [0.06531302 0.71790458]
 [0.66362309 0.35871017]
 [0.88334578 0.40370249]
 [0.60483635 0.63472026]
 [0.43783205 0.28609393]]


array([[0.60824883, 1.17397483],
       [0.34485397, 0.70722243],
       [0.7314339 , 1.2313518 ],
       [0.77598292, 0.47480678],
       [0.8445846 , 0.64143368],
       [0.72086946, 1.48006879],
       [0.75436635, 0.49554582],
       [0.97122369, 0.42867247],
       [0.87675357, 0.80950204],
       [0.52301686, 0.57878483]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [279]:
vector = np.random.rand(10)
print(vector)
vector[vector.argmax()] = 0
print(vector)

[0.67175575 0.90986828 0.49351537 0.53149251 0.28204792 0.24549262
 0.87765559 0.12899515 0.81385346 0.75812735]
[0.67175575 0.         0.49351537 0.53149251 0.28204792 0.24549262
 0.87765559 0.12899515 0.81385346 0.75812735]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [6]:
matrix = np.zeros((5,5), [('x', float), ('y', float)])
matrix['x'], matrix['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(matrix)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [292]:
X = np.array([1, 2, 3, 4])
Y = np.array([5, 6, 7, 8])

C = np.empty((len(X), len(Y)))

for i in range(len(X)):
    for j in range(len(Y)):
        C[i, j] = 1 / (X[i] - Y[j])

C

array([[-0.25      , -0.2       , -0.16666667, -0.14285714],
       [-0.33333333, -0.25      , -0.2       , -0.16666667],
       [-0.5       , -0.33333333, -0.25      , -0.2       ],
       [-1.        , -0.5       , -0.33333333, -0.25      ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [308]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    print(str(dtype) + ': ' + str(np.iinfo(dtype).min))
    print(str(dtype) + ': ' + str(np.iinfo(dtype).max))
for dtype in [np.float16, np.float32, np.float64]:
    print(str(dtype) + ': ' + str(np.finfo(dtype).min))
    print(str(dtype) + ': ' + str(np.finfo(dtype).max))
for dtype in [np.complex64, np.complex128]:
    print(str(dtype) + ': ' + str(np.finfo(dtype).min))
    print(str(dtype) + ': ' + str(np.finfo(dtype).max))

<class 'numpy.int8'>: -128
<class 'numpy.int8'>: 127
<class 'numpy.int16'>: -32768
<class 'numpy.int16'>: 32767
<class 'numpy.int32'>: -2147483648
<class 'numpy.int32'>: 2147483647
<class 'numpy.int64'>: -9223372036854775808
<class 'numpy.int64'>: 9223372036854775807
<class 'numpy.float16'>: -65500.0
<class 'numpy.float16'>: 65500.0
<class 'numpy.float32'>: -3.4028235e+38
<class 'numpy.float32'>: 3.4028235e+38
<class 'numpy.float64'>: -1.7976931348623157e+308
<class 'numpy.float64'>: 1.7976931348623157e+308
<class 'numpy.complex64'>: -3.4028235e+38
<class 'numpy.complex64'>: 3.4028235e+38
<class 'numpy.complex128'>: -1.7976931348623157e+308
<class 'numpy.complex128'>: 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [310]:
vector = np.random.rand(3)
print(vector)

for value in vector:
    print(value)

[0.96744056 0.89040133 0.85395569]
0.9674405583493703
0.890401332927417
0.8539556858505605


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [311]:
vector = np.array([1.2, 3.4, 5.6, 7.8, 9.0])

scalar = 4.0
index = np.argmin(np.abs(vector - scalar))

vector[index]

3.4

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [314]:
dtype = np.dtype([('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])])

vector = np.array([((1.0, 2.0), (255, 0, 0)), 
                    ((3.5, 4.5), (0, 128, 255)), 
                    ((0.0, 0.0), (64, 64, 64))], dtype = dtype)

print(vector)

[((1. , 2. ), (255,   0,   0)) ((3.5, 4.5), (  0, 128, 255))
 ((0. , 0. ), ( 64,  64,  64))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [11]:
vector = np.random.random((100,2))
X, Y = np.atleast_2d(vector[:, 0], vector[:, 1])
D = np.sqrt( (X - X.T)**2 + (Y - Y.T)**2)
print(D)

[[0.         0.56084048 0.99244564 ... 0.67956107 0.91994885 0.44914148]
 [0.56084048 0.         0.59968447 ... 0.43278649 0.78034292 0.26728411]
 [0.99244564 0.59968447 0.         ... 0.32852812 0.42412152 0.545723  ]
 ...
 [0.67956107 0.43278649 0.32852812 ... 0.         0.34757222 0.25521254]
 [0.91994885 0.78034292 0.42412152 ... 0.34757222 0.         0.5744436 ]
 [0.44914148 0.26728411 0.545723   ... 0.25521254 0.5744436  0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [2]:
Z = np.arange(10, dtype = np.float32)
Z = Z.astype(np.int32)
# Z = np.array(Z, dtype = np.int32)
print(Z)


[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [2]:
file = open('task54.txt', 'r')

matrix = np.genfromtxt(file, delimiter=',', dtype = float, filling_values = np.nan)

print(matrix)

file.close()

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [9]:
matrix = np.arange(9).reshape(3,3)

print(matrix)

for index, value in np.ndenumerate(matrix):
    print(f"Index: {index}, Value: {value}")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Index: (0, 0), Value: 0
Index: (0, 1), Value: 1
Index: (0, 2), Value: 2
Index: (1, 0), Value: 3
Index: (1, 1), Value: 4
Index: (1, 2), Value: 5
Index: (2, 0), Value: 6
Index: (2, 1), Value: 7
Index: (2, 2), Value: 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [39]:

size = 6
sigma = 6.0

x, y = np.meshgrid(np.linspace(-10, 10, size), np.linspace(-10, 10, size))

gaussianMatrix = np.exp(-(x**2 + y**2) / (2 * sigma**2))
gaussianMatrix /= np.max(gaussianMatrix)

print(gaussianMatrix)

[[0.06948345 0.16901332 0.26359714 0.26359714 0.16901332 0.06948345]
 [0.16901332 0.41111229 0.64118039 0.64118039 0.41111229 0.16901332]
 [0.26359714 0.64118039 1.         1.         0.64118039 0.26359714]
 [0.26359714 0.64118039 1.         1.         0.64118039 0.26359714]
 [0.16901332 0.41111229 0.64118039 0.64118039 0.41111229 0.16901332]
 [0.06948345 0.16901332 0.26359714 0.26359714 0.16901332 0.06948345]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [49]:
p = 10

rows, cols = 10, 10
shape = (rows, cols)

matrix = np.zeros(shape, dtype=int)

for _ in range(p):
    randomRow = np.random.randint(0, rows)
    randomCol = np.random.randint(0, cols)

    matrix[randomRow, randomCol] = 1

print(matrix)

[[0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [54]:
matrix = np.random.randint(0, 10, (3, 3))

print(matrix)
print()

rowMeansMatrix = np.mean(matrix, axis = 1, keepdims = True)
matrix = matrix - rowMeansMatrix

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [64]:
n = 2

matrix = np.random.randint(0,10,(4,4))

print(matrix)
print()

sortedIndices = np.argsort(matrix[:, n - 1])
matrix = matrix[sortedIndices]

print(matrix)

[[4 4 2 4]
 [6 0 5 0]
 [1 9 1 7]
 [3 2 8 0]]

[[6 0 5 0]
 [3 2 8 0]
 [4 4 2 4]
 [1 9 1 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [81]:
matrix = np.random.randint(0, 2, (3, 3))

print(matrix)

nullColumns = np.all(matrix == 0, axis = 0)
print(nullColumns)

if np.any(nullColumns):
    print("Null column indices:", np.where(nullColumns)[0])
else:
    print("The array does not have null columns.")

[[0 0 1]
 [0 0 0]
 [1 0 0]]
[False  True False]
Null column indices: [1]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [97]:
vector = np.linspace(0, 21, 7) 

print(array)

givenValue = 6

absoluteDifferences = np.abs(vector - givenValue)
index = np.argmin(absoluteDifferences)
nearestValue = vector[index]

print("Given Value:", givenValue)
print("Nearest Value:", nearestValue)

[ 0.   3.5  7.  10.5 14.  17.5 21. ]
Given Value: 6
Nearest Value: 7.0


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [110]:
n1 = 3
n2 = 3

vector1 = np.random.randint(0, 5, (1, n1))
vector2 = np.random.randint(0, 5, (n2, 1))

print(vector1)
print()
print(vector2)
print()

result = np.zeros((n1, n2))

for i in range(n1):
    for j in range(n2):
        result[i, j] = vector1[i % 1, j % n1] + vector2[i % n2, j % 1]

print(result)

[[0 3 4]]

[[0]
 [4]
 [3]]

[[0. 3. 4.]
 [4. 7. 8.]
 [3. 6. 7.]]


#### 63. Create an array class that has a name attribute (★★☆)

In [122]:
class NamedArray(np.ndarray):
    def __new__(cls, inputArray, name = None):
        # Create a new instance of the array class
        obj = np.asarray(inputArray).view(cls)
        
        # Add the 'name' attribute
        obj.name = name
        
        return obj

    def __array_finalize__(self, obj):
        # This method is called during the creation of a new array instance
        if obj is None: return
        # Copy the 'name' attribute from the original object (if any)
        self.name = getattr(obj, 'name', None)

namedVector = NamedArray(np.arange(10), name = 'ExampleVector')

print(namedVector.name)
print(namedVector)

ExampleVector
[0 1 2 3 4 5 6 7 8 9]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [131]:
vector = np.arange(7)

print("Original vector:", vector)

indices = np.array([1, 3, 4, 1, 5])

print("Indeces:",indices)

for index in np.unique(indices):
    vector[index] += 1

print("Result:",vector)

Original vector: [0 1 2 3 4 5 6]
Indeces: [1 3 4 1 5]
Result: [0 2 2 4 5 6 6]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [134]:
X = np.array([1, 2, 3, 4, 5])
F = np.zeros(10)
I = np.array([2, 5, 1, 2, 9])

np.add.at(F, I, X)

print("X:", X)
print("I:", I)
print("F:", F)

X: [1 2 3 4 5]
I: [2 5 1 2 9]
F: [0. 3. 5. 0. 0. 2. 0. 0. 0. 5.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [18]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis = 0)
print(len(colors))

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [148]:
fourDArray = np.random.rand(2, 2, 4, 5)

sum = np.sum(fourDArray, axis = (2, 3))

print(sum)

[[10.95828198 10.65719696]
 [ 7.59840164  9.86348818]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [25]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
DSums = np.bincount(S, weights = D)
DCounts = np.bincount(S)
DMeans = DSums / DCounts
print(DMeans)

[0.65302297 0.54598766 0.48934718 0.59626553 0.58878937 0.58061708
 0.58145326 0.54784279 0.64503957 0.50528122]


#### 69. How to get the diagonal of a dot product? (★★★)

In [8]:

A = np.random.randint(0, 10, (3, 3))
B = np.random.randint(0, 10, (3, 3))

dotProduct = np.dot(A, B)
diagonal = np.diag(dotProduct)

print("A:\n", A)
print("B:\n", B)
print("Dot Product:\n", dotProduct)
print("Diagonal:\n", diagonal)

A:
 [[1 7 7]
 [5 4 5]
 [4 4 7]]
B:
 [[6 8 8]
 [1 8 6]
 [4 1 8]]
Dot Product:
 [[ 41  71 106]
 [ 54  77 104]
 [ 56  71 112]]
Diagonal:
 [ 41  77 112]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [12]:
vector = [1, 2, 3, 4, 5]
newVector = []

for index in np.arange(len(vector)):
    newVector.append(vector[index])
    if (index != len(vector) - 1):
        newVector.extend([0, 0, 0])

print(newVector)

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [402]:
matrix3d = np.random.randint(1 , 10, (5, 5, 3))
matrix2d = np.random.randint(1 , 10, (5, 5))

result = matrix3d * matrix2d[:, :, np.newaxis]

print(result)

[[[ 6  6 27]
  [30 24 36]
  [25 25 20]
  [ 7 56 28]
  [ 9 54 63]]

 [[ 2  3  3]
  [72 36 63]
  [64 56 56]
  [18 18  6]
  [42 42 14]]

 [[12  4  6]
  [16  8 14]
  [ 8  6 12]
  [ 9 18 27]
  [ 6  2 12]]

 [[ 6  9  8]
  [42 54 54]
  [40  8 72]
  [ 8  9  2]
  [ 8 24 56]]

 [[12 12 21]
  [21 63 14]
  [56 42 28]
  [16 28 32]
  [54 12 54]]]


#### 72. How to swap two rows of an array? (★★★)

In [3]:
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

row1Index = 0
row2Index = 2

matrix[[row1Index, row2Index]] = matrix[[row2Index, row1Index]]

print(matrix)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [33]:
triplets = np.random.randint(0, 10, (10, 3))
F = np.roll(triplets.repeat(2, axis = 1), -1, axis = 1)
F = F.reshape(len(F)*3,2)
F = np.sort(F, axis = 1)
G = F.view( dtype=[('p0', F.dtype), ('p1', F.dtype)] )
G = np.unique(G)
print(G)

[(0, 1) (0, 2) (0, 4) (0, 5) (0, 6) (1, 1) (1, 4) (2, 4) (2, 6) (2, 9)
 (4, 5) (4, 6) (4, 8) (4, 9) (5, 6) (5, 8) (6, 6) (6, 7) (6, 9) (7, 9)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [5]:
# Given sorted array C
C = np.arange(10)

# Create array A based on C
A = np.repeat(np.arange(len(C)), C)

# Verify that np.bincount(A) == C
result = np.bincount(A) == C

print("Array C:", C)
print("Array A:", A)
print("np.bincount(A) == C:", result.all())

Array C: [0 1 2 3 4 5 6 7 8 9]
Array A: [1 2 2 3 3 3 4 4 4 4 5 5 5 5 5 6 6 6 6 6 6 7 7 7 7 7 7 7 8 8 8 8 8 8 8 8 9
 9 9 9 9 9 9 9 9]
np.bincount(A) == C: True


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [13]:
def slidingWndowAverage(vector, windowSize):
    averages = []
    
    for i in range(len(vector) - windowSize + 1):
        window = vector[i:i + windowSize]
        average = np.mean(window)
        averages.append(average)
    
    return np.array(averages)

vector = np.arange(10)
windowSize = 3

averages = slidingWndowAverage(vector, windowSize)

print(vector)
print(averages)

[0 1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [3]:
Z = np.arange(5)

numColumns = 3
numRows = len(Z) - numColumns + 1

result = np.zeros((numRows, numColumns))

for i in range(numRows):
    result[i] = Z[i:i + numColumns]

print(Z)
print()
print(result)

[0 1 2 3 4]

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [28]:
boolean = True
nBoolean = not boolean

print(boolean)
print(nBoolean)

pFloat = 3.14
nPFloat = -pFloat

print(pFloat)
print(nPFloat)

True
False
3.14
-3.14


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [410]:
def distanceToLines(P0, P1, p):
    direction = P1 - P0
    v = p - P0

    projection = np.sum(v * direction, axis=1) / np.sum(direction**2, axis=1)

    distances = np.linalg.norm(v - projection[:, np.newaxis] * direction, axis=1)
    
    return distances

P0 = np.array([[1, 1], [1, 2], [3, 6]])
P1 = np.array([[4, 4], [5, 4], [6, 5]])
p = np.array([2, 3])

distances = distanceToLines(P0, P1, p)

print(distances)

[0.70710678 0.4472136  3.16227766]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [411]:
def distanceToLines(P0, P1, P):
    direction = P1 - P0
    v = P[:, np.newaxis, :] - P0

    projection = np.sum(v * direction, axis=2) / np.sum(direction**2, axis=1)

    distances = np.linalg.norm(v - projection[:, :, np.newaxis] * direction, axis=2)

    return distances

P0 = np.array([[1, 1], [1, 2], [3, 7]])
P1 = np.array([[4, 4], [5, 3], [6, 5]])
P = np.array([[2, 3], [4, 4], [5, 6]])

distances = distanceToLines(P0, P1, P)

print(distances)

[[0.70710678 0.72760688 3.88290137]
 [0.         1.21267813 1.94145069]
 [0.70710678 2.9104275  0.2773501 ]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [7]:
def extract_subpart(matrix, shape, center, fillValue):
    matrixShape = matrix.shape

    startRow = max(0, center[0] - shape[0] // 2)
    endRow = min(matrixShape[0], center[0] + shape[0] // 2 + 1)
    startCol = max(0, center[1] - shape[1] // 2)
    endCol = min(matrixShape[1], center[1] + shape[1] // 2 + 1)

    subpart = np.full(shape, fillValue)

    sourceStartRow = shape[0] // 2 - (center[0] - startRow)
    sourceEndRow = shape[0] // 2 + (endRow - center[0])
    sourceStartCol = shape[1] // 2 - (center[1] - startCol)
    sourceEndCol = shape[1] // 2 + (endCol - center[1])

    subpart[sourceStartRow:sourceEndRow, sourceStartCol:sourceEndCol] = matrix[startRow:endRow, startCol:endCol]

    return subpart

matrix = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

shape = (3, 3)
center = (2, 2)
fillValue = 0

subpart = extract_subpart(matrix, shape, center, fillValue)
print(subpart)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [29]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

numColumns = 4
numRows = len(Z) - numColumns + 1

result = np.zeros((numRows, numColumns))

for i in range(numRows):
    result[i] = Z[i:i + numColumns]

print(Z)
print()
print(result)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[[ 1.  2.  3.  4.]
 [ 2.  3.  4.  5.]
 [ 3.  4.  5.  6.]
 [ 4.  5.  6.  7.]
 [ 5.  6.  7.  8.]
 [ 6.  7.  8.  9.]
 [ 7.  8.  9. 10.]
 [ 8.  9. 10. 11.]
 [ 9. 10. 11. 12.]
 [10. 11. 12. 13.]
 [11. 12. 13. 14.]]


#### 82. Compute a matrix rank (★★★)

In [105]:
matrix = np.random.randint(1, 3, (3, 3))

rank = np.linalg.matrix_rank(matrix)


print(matrix)
print()
print(rank)

[[2 2 1]
 [1 2 1]
 [1 1 1]]

3


#### 83. How to find the most frequent value in an array?

In [111]:
arr = np.random.randint(1, 10, (10))

uniqueValues, counts = np.unique(arr, return_counts = True)
index = np.argmax(counts)
value = uniqueValues[index]

print(arr)
print(value)

[8 3 8 2 3 4 6 8 9 3]
3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [121]:
matrix = np.random.randint(1, 10, (10, 10))
print(matrix)
print()

blockSize = 3

blocks = []

for i in range(10 - blockSize + 1):
    for j in range(10 - blockSize + 1):
        block = matrix[i:i + blockSize, j:j + blockSize]
        blocks.append(block)


for i, block in enumerate(blocks):
    print(f"Block {i + 1}:\n{block}\n")

[[3 3 2 9 4 2 6 6 3 6]
 [4 7 9 7 1 1 4 7 9 8]
 [1 3 6 9 3 7 4 2 8 6]
 [9 5 1 6 3 9 6 3 2 5]
 [6 7 8 9 3 7 5 6 1 5]
 [6 6 4 3 6 3 5 8 4 3]
 [6 7 5 2 1 5 4 8 8 6]
 [8 7 6 9 9 8 2 3 7 2]
 [4 5 9 2 1 9 1 3 9 6]
 [3 7 6 4 9 5 8 3 1 5]]

Block 1:
[[3 3 2]
 [4 7 9]
 [1 3 6]]

Block 2:
[[3 2 9]
 [7 9 7]
 [3 6 9]]

Block 3:
[[2 9 4]
 [9 7 1]
 [6 9 3]]

Block 4:
[[9 4 2]
 [7 1 1]
 [9 3 7]]

Block 5:
[[4 2 6]
 [1 1 4]
 [3 7 4]]

Block 6:
[[2 6 6]
 [1 4 7]
 [7 4 2]]

Block 7:
[[6 6 3]
 [4 7 9]
 [4 2 8]]

Block 8:
[[6 3 6]
 [7 9 8]
 [2 8 6]]

Block 9:
[[4 7 9]
 [1 3 6]
 [9 5 1]]

Block 10:
[[7 9 7]
 [3 6 9]
 [5 1 6]]

Block 11:
[[9 7 1]
 [6 9 3]
 [1 6 3]]

Block 12:
[[7 1 1]
 [9 3 7]
 [6 3 9]]

Block 13:
[[1 1 4]
 [3 7 4]
 [3 9 6]]

Block 14:
[[1 4 7]
 [7 4 2]
 [9 6 3]]

Block 15:
[[4 7 9]
 [4 2 8]
 [6 3 2]]

Block 16:
[[7 9 8]
 [2 8 6]
 [3 2 5]]

Block 17:
[[1 3 6]
 [9 5 1]
 [6 7 8]]

Block 18:
[[3 6 9]
 [5 1 6]
 [7 8 9]]

Block 19:
[[6 9 3]
 [1 6 3]
 [8 9 3]]

Block 20:
[[9 3 7]
 [6 3 9]
 [9 3 7]

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [146]:
class SymmetricArray(np.ndarray):
    def __new__(cls, array):
        array = np.asarray(array)

        obj = np.empty_like(array, dtype = array.dtype)

        for i in range(array.shape[0]):
            for j in range(i, array.shape[1]):
                obj[i, j] = obj[j, i] = array[i, j]

        obj = obj.view(cls)
        return obj
    
    def __setitem__(self, index, value):
        i, j = index
        super().__setitem__((i, j), value)
        super().__setitem__((j, i), value)

matrix = np.arange(9).reshape((3, 3))
symetrixMatrix = SymmetricArray(matrix)

print(matrix)
print()
print(symetrixMatrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2]
 [1 4 5]
 [2 5 8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [40]:
p, n = 10, 20
matrices = np.ones((p, n, n))
vectors = np.ones((p, n, 1))
sum = np.tensordot(matrices, vectors, axes = [[0, 2], [0, 1]])
print(sum)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [169]:
matrixSize = 16

matrix = np.random.randint(1, 10, (matrixSize, matrixSize))
print(matrix)
print()

blockSize = 4

blocksSum = np.zeros((blockSize, blockSize), dtype = matrix.dtype)

for i in range(matrixSize - blockSize + 1):
    for j in range(matrixSize - blockSize + 1):
        block = matrix[i:i + blockSize, j:j + blockSize]
        blocksSum += block

print(blocksSum)

[[5 4 3 3 7 6 5 9 1 1 5 4 1 9 2 2]
 [6 7 4 4 1 2 9 5 6 7 4 1 3 3 7 6]
 [2 2 7 5 9 8 9 7 5 8 3 8 7 7 1 6]
 [6 8 1 5 1 5 1 1 8 1 5 9 2 8 6 4]
 [2 3 1 4 3 2 5 5 8 8 8 1 8 4 6 4]
 [7 2 6 5 6 4 9 7 3 3 4 3 9 5 2 4]
 [6 3 3 4 5 1 1 5 2 6 7 2 4 6 7 9]
 [8 3 5 9 8 7 4 3 5 6 2 5 5 8 8 5]
 [7 1 2 2 2 2 7 5 3 2 9 1 1 6 9 3]
 [2 8 2 8 8 6 9 7 8 9 8 6 6 4 9 3]
 [1 8 2 8 6 9 1 9 9 3 5 1 8 5 6 1]
 [1 7 6 3 3 3 2 7 8 9 4 7 5 6 8 7]
 [3 8 7 8 1 6 8 5 8 1 3 2 1 6 8 1]
 [7 9 2 3 8 5 6 9 4 6 9 3 2 9 3 3]
 [2 7 7 3 7 4 7 2 9 3 7 8 7 7 8 7]
 [1 6 7 5 4 3 2 8 4 2 7 7 8 8 6 4]]

[[818 839 854 860]
 [837 856 867 875]
 [851 878 890 896]
 [835 864 877 881]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [73]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0, 2, (10,10))

for i in range(100): 
    Z = iterate(Z)
    print(Z)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 1 0 1 0 0 0 1 1 0]
 [0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 1 1 0]
 [0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 1 1 1 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0]
 [0 0 1 0 0 0 0 1 1 0]
 [0 0 1 1 1 0 0 0 0 0]
 [0 0 0 1 1 0 0 1 1 0]
 [0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0]
 [0 0 1 0 0 0 0 1 1 0]
 [0 0 1 0 1 0 0 0 0 0]
 [0 0 1 0 0 1 0 1 1 0]
 [0 0 0 0 1 1 1 0 1 0]
 [0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0]
 [0 0 0 1 0 0 0 1 1 0]
 [0 1 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0]
 [0 0 1 0 0 0 1 0 1 0]
 [0 0 1

#### 89. How to get the n largest values of an array (★★★)

In [181]:
vector = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

n = 3

indices = np.argpartition(vector, -n)[-n:]

largestValues = vector[indices]

print(vector)
print(largestValues)

[3 1 4 1 5 9 2 6 5 3]
[5 6 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [187]:
vector1 = np.arange(1, 4)
vector2 = np.arange(4, 7)
vector3 = np.arange(7, 10)

vectors = [vector1, vector2, vector3]

meshgrids = np.meshgrid(*vectors, indexing='ij')

cartesianProduct = np.meshgrid(meshgrids, axis=-1)

numRows = np.prod([vector.size for vector in vectors])
cartesianProduct = cartesianProduct.reshape((numRows, len(vectors)))

print(cartesianProduct)

[[1 4 7]
 [1 4 8]
 [1 4 9]
 [1 5 7]
 [1 5 8]
 [1 5 9]
 [1 6 7]
 [1 6 8]
 [1 6 9]
 [2 4 7]
 [2 4 8]
 [2 4 9]
 [2 5 7]
 [2 5 8]
 [2 5 9]
 [2 6 7]
 [2 6 8]
 [2 6 9]
 [3 4 7]
 [3 4 8]
 [3 4 9]
 [3 5 7]
 [3 5 8]
 [3 5 9]
 [3 6 7]
 [3 6 8]
 [3 6 9]]


#### 91. How to create a record array from a regular array? (★★★)

In [36]:
vector = np.array([(1, 'John', 25), 
                   (2, 'Alice', 30), 
                   (3, 'Bob', 28)], 
                  dtype=[('id', int), ('name', 'U10'), ('age', int)])

recordVector = np.rec.array(vector)

print("ID:", recordVector.id)
print("Name:", recordVector.name)
print("Age:", recordVector.age)

ID: [1 2 3]
Name: ['John' 'Alice' 'Bob']
Age: [25 30 28]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [201]:
Z = np.random.randint(1, 10, (1000000))
print(Z)
print()

result1 = Z ** 3
result2 = np.power(Z, 3)
result3 = np.multiply(np.multiply(Z, Z), Z)

print(result1)
print(result2)
print(result3)

[4 5 1 ... 7 3 3]

[ 64 125   1 ... 343  27  27]
[ 64 125   1 ... 343  27  27]
[ 64 125   1 ... 343  27  27]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [267]:
A = np.random.randint(1, 10, (8, 3))
B = np.random.randint(1, 10, (2, 2))

print(A)
print()
print(B)
print()

setsB = [set(row) for row in B]

results = []

for rowA in A:
    for setsBRow in setsB:
        if set(rowA).issuperset(setsBRow):
            results.append(rowA)

for result in results:
    print(result)

if results == []:
    print('Nothing')

[[5 3 9]
 [8 6 7]
 [4 8 5]
 [4 1 7]
 [7 4 7]
 [8 4 8]
 [2 5 6]
 [5 1 6]]

[[5 2]
 [7 3]]

[2 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [32]:
matrix = np.random.randint(1, 3, (10, 3))

print(matrix)
print()

equalRows = np.all(matrix[:, 1:] == matrix[:, :-1], axis=1)
unequalRows = ~equalRows

result = matrix[unequalRows]

print(result)

[[1 2 2]
 [2 1 1]
 [2 1 1]
 [2 2 2]
 [1 2 2]
 [2 2 2]
 [2 2 2]
 [1 2 2]
 [2 2 2]
 [1 2 2]]

[[1 2 2]
 [2 1 1]
 [2 1 1]
 [1 2 2]
 [1 2 2]
 [1 2 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [31]:
vector = np.random.randint(0, 10, (5))

maxBits = int(np.ceil(np.log2(np.max(vector) + 1)))
matrix = np.array([list(np.binary_repr(num, width = maxBits)) for num in vector], dtype = int)

print(vector)
print()
print(matrix)

[1 9 7 9 6]

[[0 0 0 1]
 [1 0 0 1]
 [0 1 1 1]
 [1 0 0 1]
 [0 1 1 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [306]:
matrix = np.random.randint(1, 3, (5, 3))

uniqueRows = np.unique(matrix, axis = 0)

print(matrix)
print()
print(uniqueRows)

[[2 2 2]
 [2 2 2]
 [1 1 2]
 [2 2 1]
 [2 2 2]]

[[1 1 2]
 [2 2 1]
 [2 2 2]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [30]:
A = np.random.randint(1, 10, (3))
B = np.random.randint(1, 10, (3))

print(A)
print(B)
print()

print('inner: ', np.einsum('i,i->', A, B))
print('outer: ', np.einsum('i,j->ij', A, B))
print('sum: ', np.einsum('i->i', A) + np.einsum('i->i', B))
print('mul: ', np.einsum('i,i->i', A, B))

[1 6 6]
[4 3 8]

inner:  70
outer:  [[ 4  3  8]
 [24 18 48]
 [24 18 48]]
sum:  [ 5  9 14]
mul:  [ 4 18 48]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [29]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a * phi * np.cos(phi)
y = a * phi * np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
rInt = np.linspace(0, r.max(), 200)
xInt = np.interp(rInt, r, x)
yInt = np.interp(rInt, r, y)

print(xInt)
print(yInt)

[ 0.00000000e+00 -3.73131229e-01 -2.59817608e+00 -3.26212050e+00
 -2.18442687e+00 -2.98929946e-02  2.42923642e+00  4.54913599e+00
  5.92318348e+00  6.35117933e+00  5.82369277e+00  4.46259540e+00
  2.47320794e+00  1.09577220e-01 -2.36575300e+00 -4.71261671e+00
 -6.72701769e+00 -8.25541575e+00 -9.18486120e+00 -9.46381505e+00
 -9.11085788e+00 -8.12875279e+00 -6.63306046e+00 -4.69271059e+00
 -2.44736165e+00 -2.05444585e-02  2.46101146e+00  4.86841760e+00
  7.08937968e+00  9.02539126e+00  1.05948609e+01  1.17357250e+01
  1.24068974e+01  1.25885805e+01  1.22815267e+01  1.15053927e+01
  1.02963689e+01  8.70429550e+00  6.78948686e+00  4.61716636e+00
  2.25853448e+00 -1.98731680e-01 -2.68040566e+00 -5.11543300e+00
 -7.41973991e+00 -9.53891040e+00 -1.14237629e+01 -1.29919305e+01
 -1.42355069e+01 -1.51243232e+01 -1.56061571e+01 -1.57219415e+01
 -1.54217066e+01 -1.47579136e+01 -1.37255236e+01 -1.23634834e+01
 -1.07024632e+01 -8.78327367e+00 -6.65029558e+00 -4.35514246e+00
 -1.94290275e+00  5.28038

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [61]:
X = np.random.randint(0, 3, (10, 4))

print(X)
print()

n = 4

rows = np.logical_and(np.all(X % 1 == 0, axis=1), np.sum(X, axis=1) == n)

selectedRows = X[rows]

print(selectedRows)

[[1 1 0 1]
 [2 2 1 2]
 [1 2 2 0]
 [0 1 2 1]
 [0 1 2 1]
 [0 2 2 0]
 [0 0 1 0]
 [1 1 1 2]
 [2 1 0 1]
 [2 1 0 1]]

[[0 1 2 1]
 [0 1 2 1]
 [0 2 2 0]
 [2 1 0 1]
 [2 1 0 1]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [58]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
confint

array([-0.36187644, -0.01003685])